substitutions:
    device_name: "window-motor-bed1-left"
    device_entity: 'window-motor-bed1-left'
    friendly_name: 'Window Motor Bed 1 Left'
    operation_duration: "30"
    command_duration: "5"
    
<<: !include window-motor-base2.yaml
