substitutions:
    device_name: "window-motor-bed1-right"
    device_entity: 'window-motor-bed1-right'
    friendly_name: 'Window Motor Bed 1 right'
    operation_duration: "30"
    command_duration: "5"
    
<<: !include window-motor-base2.yaml
